[IV-24-25] Problema planteado
hossam1522/ModaTrack pull request #1
Opened 2024-09-23 11:23 UTC by hossam1522

* [x] ¿Se trata de un problema real del que se tenga conocimiento personal?

 Sí, tengo varios familiares trabajando en tiendas de ropa o en cosas relacionadas con ello.

* [x] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?

Sí, debido a la accesibilidad desde cualquier dispositivo y el almacenamiento y procesamiento de grandes volúmenes de datos, aparte de la necesidad de disponibilidad.

* [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?

Sí. Por ejemplo, para obtener las estadísticas de ventas y saber qué prendas son más rentables o no.

* [x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
`README`?
* [x] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?

Los datos se obtendrían de los familiares que trabajan en este tipo de negocios. Además, en caso de ser necesario, se podría usar la IA generativa para generar datos de mejor calidad.

* [x] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
todo?

2024-09-23 15:47 UTC, JJ commented
> * [x]  ¿Se trata de un problema real del que se tenga conocimiento personal?
> 
> 
> Sí, tengo varios familiares trabajando en tiendas de ropa o en cosas relacionadas con ello.
> 
>     * [x]  ¿Se trata de un problema que para solucionar requiera el despliegue
>       de una aplicación en la nube?
> 
> 
> Sí, debido a la accesibilidad desde cualquier dispositivo y el almacenamiento y procesamiento de grandes volúmenes de datos, aparte de la necesidad de disponibilidad.
> 
>     * [x]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
>       solucionarse sólo almacenando y buscando?
> 
> 
> Sí. Por ejemplo, para obtener las estadísticas de ventas y saber qué prendas son más rentables o no.
> 
>     * [x]  ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
>       `README`?

Si no la has incluido, es que o no has entendido la pregunta o estás marcando todo. En cualquiera de los casos has marcado indebidamente esto, añadiéndonos a los dos trabajo adicional, porque tendrás que de todas formas que hacer lo que te pide en la lista de comprobación y yo que comprobarlo de nuevo. Como dice en [errores frecuents](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md)

> a lista de comprobación es imprescindible, porque te permite saber si lo que estás haciendo es efectivo o no y te ahorra trabajo tanto al estudiante (que no tendrá que revisar y enviar de nuevo) como al profesor. Pásala y compruébala.

Te rogaría que trataras de usarla como tal, una lista de comprobación que nos ayuda a los dos (pero sobre todo a ti) a realizar la entrega correctamente, no "una cosa que pide el profesor y que ni sé por qué la pide ni me preocupa". Como os pues en el vídeo el primer día, en ingeniería (y en esta asignatura también tratamos de que sea así) siempre tienes que entender el por qué, o preguntar el por qué si no lo entiendes.

> 
>     * [x]  ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
>       a requerir que el usuario los introduzca?
> 
> 
> Los datos se obtendrían de los familiares que trabajan en este tipo de negocios. Además, en caso de ser necesario, se podría usar la IA generativa para generar datos de mejor calidad.
> 
>     * [x]  ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
>       todo?

¿Cuál de los dos?

2024-09-23 20:56 UTC, hossam1522 commented
¿Me podría volver a revisar, @JJ? Gracias de antemano.

2024-09-24 05:27 UTC, JJ requested changes
Entender el problema es fundamental, porque nunca hay una sola forma de resolverlo. Las estadísticas o tener el control del stock puede ayudar, o simplemente aumentar la carga cognitiva de la persona que tiene la tienda. Pero en todo caso el problema tiene que formularse de tal forma que se pueda llegar al objetivo 4 y hacer tests para comprobar si, con la lógica de negocio de tu programa, se han resuelto o no. "Quiero hacer estadísticas" no se puede testear.  Como dice en [el guión del objetivo](http://jj.github.io/IV/documentos/proyecto/0.Repositorio)

> Por eso es esencial que sea no trivial, para que los tests efectivamente comprueben que se está resolviendo el problema correctamente.

2024-09-24 05:27 UTC, JJ commented on README.md
> +Soy un vendedor de ropa al que le cuesta mucho mantener un control de su inventario. Tengo una tienda de ropa y me gustaría tener un sistema que me permita llevar un control de las ventas y del inven
Está bien que se trate de un problema del que tengas conocimiento personal, así está más cerca de superarse el objetivo.

Pero hay una enumeración de cosas que se "quieren" hacer, pero no acabo de ver "el problema". Como habrás visto en [la lista de errores comunes](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md):

> Si se describe lo que el cliente quiere hacer sin decir por qué quiere hacerlo, no estás describiendo el problema, estás describiendo una solución. Es imposible de esa forma iniciar un proceso de desarrollo de una solución, que requiere de un problema.

Si describes lo que quiere hacer en vez de por qué quiere hacer eso, no estás describiendo el problema, sino la solución. Y el cliente, en principio, no sabe solucionar el problema, para eso está el ingeniero. Pero el ingeniero no entiende el problema, así que cuando haga la aplicación podrá solucionar el problema o no, pero más bien no porque no sabe cuál es el problema.

Si quieres llegar al problema, tienes que preguntarte "por qué" en el vídeo. ¿Por qué quiere llevar control de las ventas? ¿Quiere vender más? ¿Tener menos cosas en el almacén? ¿Tener cosas en el almacén cuesta dinero? ¿Por qué quieres saber el stock? ¿Quieres tener un stock mínimo? ¿Máximo? ¿Cada cuanto se puede reponer el stock? ¿Qué es un mayor problema? ¿Tener mucho stock o tener poco stock?

2024-09-24 21:19 UTC, hossam1522 commented
Solicito de nuevo una revisión, @JJ. Gracias de antemano.

2024-09-25 06:29 UTC, JJ requested changes
La parte donde formulas el problema estaría correcta, aunque podrías considerar eliminar las partes en las que he comentado algo (posiblemente dejarlas para el objetivo 1, o no). Pero sigues sin incluir la [configuración](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#explicaci%C3%B3n), tal como se explica en el guión (y lo que incluyes no lo has hecho correctamente, porque le falta una extensión de imagen o algo)
Ánimo, que ya estás más cerca.

2024-09-25 06:29 UTC, JJ commented on README.md
> +- Ineficiencia en la reposición de productos: Actualmente, no tengo un sistema que me avise cuándo reponer el stock, lo que genera retrasos en los pedidos y problemas con el abastecimiento de product
Como te he dicho antes, la formulación de un problema es la guía para hacer un modelo del mismo y eventualmente solucionarlo. Si hablas de "ineficiencia" tendrás que hacer un test en el objetivo 4 que compruebe que lo que propones es más eficiente. Es más, tendrás que tener un modelo de como se hace *ahora* para comprobar que tu solución es mejor.
En todo caso, esto es una consecuencia del anterior, ¿no? ¿Podrías considerar quedarte inicialmente solo con una descripción precisa, pero también concisa, del problema?

2024-09-25 06:29 UTC, JJ commented on README.md
> +- Falta de datos para la toma de decisiones: No tengo estadísticas claras de qué productos se venden más o con cuáles se obtiene mayor beneficio, lo que dificulta planificar qué ropa debo priorizar e
¿No estarás tratando de formular como un problema lo que te he dicho antes que es una solución?

2024-09-25 21:28 UTC, hossam1522 commented
Solicito de nuevo una revisión, @JJ. Gracias de antemano.

2024-09-26 07:15 UTC, JJ approved these changes
👍

2024-09-26 07:25 UTC, merged