[IV-24-25] Entrega Objetivo 1
hossam1522/ModaTrack pull request #7
Opened 2024-09-30 11:47 UTC by hossam1522

Sobre los milestones

* [x] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [x] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [x] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [x] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [x] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [x] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [x] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [x] ¿El milestone 0 es mínimo *y* viable?
* [x] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [x] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

Sobre las historias de usuario

* [x] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [x] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [x] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2024-09-30 19:14 UTC, mmnuria reviewed
Quitando lo mencionado, me parece que queda muy bien explicado cada parte y lo que se pretende realizar en cada hito queda bien reflejado. Es cierto que, a lo mejor el milestone 1, lo dividiría en 2, para que se asegure más el concepto de producto minimamente viable, ya que, creo que abarca demasiadas funcionalidades.

2024-09-30 19:14 UTC, mmnuria commented on docs/milestones.md
Faltaría mencionar en cada milestone que historia de usuario se le asocia, simplemente en el titulo con poner por ejemplo: "[M0] Milestone 0: Modelado del problema (HU001)" en caso de que se le asocie la historia de usuario 1 y así con todos.

2024-09-30 19:14 UTC, mmnuria commented on docs/user_stories.md
El nombre de cada historia de usuario [debe](https://jj.github.io/IV/documentos/proyecto/1.Planificacion#explicaci%C3%B3n) de escribirse como [HU001] Dueño de tienda, [HU002]...

2024-09-30 19:14 UTC, mmnuria commented on docs/user_journeys.md
> +Por último, cuando llega un cambio de temporada, tengo que estar pendiente de cambiar la ropa de la tienda, ya que la ropa de verano no se vende en invierno y viceversa. Es importante tener claro qué
Aquí hay una errata, en lugar de "Repitp" sería "Repito"

2024-10-01 07:56 UTC, juanmaaf reviewed
Buenas, se me ha asignado revisar tu PR. Basándome en la lista de comprobación, generalmente lo veo bien, aunque he hecho unas pequeñas puntualizaciones en la explicación de los Milestones.

2024-10-01 07:56 UTC, juanmaaf commented on docs/milestones.md
> +### [M1] Milestone 1: Auditoría completa del inventario
Los milestones están bien definidos, incluyendo la explicación de la viabilidad del PMV para cada uno de los hitos. Sin embargo, ¿no hay un salto demasiado grande entre M0 y M1? ¿O acaso consideras que M1 es un producto "mínimo"? Se han creado en el repositorio y además tienen asignada alguna historia de usuario. Podrías considerar incluir las historias asociadas a cada hito en este documento. Finalmente, ten en cuenta que la metodología de desarrollo ágil te hará descubrir cómo resolver tu problema. Puede ser adecuado establecer menos hitos, o indicarlos como adicionales.

2024-10-01 07:56 UTC, juanmaaf commented on docs/user_stories.md
> +# User Stories
Las historias de usuario están muy bien definidas y quedan aclaradas gracias a los user journeys. Junto a los milestones, constituyen una buena guía para el desarrollo del proyecto.

2024-10-01 09:03 UTC, antoniorr02 commented
Buenas me han asignado a revisar tu PR.

No tengo nada más que añadir a las correcciones de mis compañeros @mmnuria y @juanmaaf

2024-10-01 21:06 UTC, hossam1522 commented on docs/milestones.md
Hola! A la hora de mirar los milestones en GitHub, salen las issues que están asociadas a estos. En principio, todas las issues están asociadas al milestone 0 para el modelado del problema y luego se irán distribuyendo según corresponda, tal y como se menciona aquí:

```
Alguna HUs tendrá que asignarse al siguiente milestone, aunque se podrán ir moviendo durante el avance del proyecto; de esta forma se prioriza una HU frente a las otras para comenzar a desarrollar.
```

Considerando que el siguiente milestone es el 0. Además, en principio no deja asignar issues a milestones diferentes.

No sé si te referías a eso. Si me equivoco, por favor, corrígeme.

2024-10-01 21:07 UTC, hossam1522 commented on docs/user_stories.md
¿No se refiere a que debe estar así escrito en la issue y no tanto en la documentación? Igualmente, lo modifico.

2024-10-01 21:08 UTC, hossam1522 commented on docs/user_journeys.md
> +Por último, cuando llega un cambio de temporada, tengo que estar pendiente de cambiar la ropa de la tienda, ya que la ropa de verano no se vende en invierno y viceversa. Es importante tener claro qué
Cierto, lo arreglo. Gracias!

2024-10-01 21:11 UTC, hossam1522 commented on docs/milestones.md
> +### [M1] Milestone 1: Auditoría completa del inventario
Hola! Puede ser que el milestone 1 sea demasiado avaricioso. Igualmente es algo que me gustaría consultar con el profesor. En cuanto a incluir las historias asociadas en el propio documento, en principio he decidido no hacerlo debido a la posibilidad de que estas historias vayan cambiando de lugar a lo largo del desarrollo del proyecto.

2024-10-01 21:15 UTC, hossam1522 commented
Muchas gracias por las revisiones @mmnuria @juanmaaf @antoniorr02! Os he dejado algunas respuestas en los comentarios que me habéis dejado. Así por lo general saco 2 conclusiones:

- Quizás el milestone 1 es demasiado grande y avaricioso, aunque es algo que quiero consultar con el profesor a poder ser.
- Quizás hay demasiados milestones y debería dejar alguno como adicional, cosa que también quiero consultar.

Las demás cosas mencionadas las modificaré en breves. Muchas gracias de nuevo!

2024-10-02 09:41 UTC, mmnuria commented on docs/user_stories.md
Creo recordar que me mencionó en clase que el objetivo 1 es para añadir todo a la documentación y así poder revisarlo y modificarlo sin necesidad de realizar tantos commits, de igual manera, nunca esta de más la información en la documentación, cuanto más clara siempre mejor!! :)

2024-10-02 09:43 UTC, mmnuria commented on docs/milestones.md
Hola, siii, pero en la documentación no queda del todo claro, es a lo que me refería! Simplemente añadir o mencionar en la documentación que milestone corresponde a que HU, para que se pueda determinar mejor si cumple con PMV y con las necesidades del usuario.

2024-10-03 07:28 UTC, mmnuria reviewed
Te he añadido alguna información extra que puede ser util, para conseguir el apto por mi parte (si te sirve de consuelo, estoy igual que tu, es decir, buscando que metodología asignar a mi proyecto).

2024-10-03 07:28 UTC, mmnuria commented on docs/milestones.md
> +### [M0] Milestone 0: Modelado del problema
Acabo de comentar esto mismo con el profesor, y el concepto de "modelado" no se puede considera como PMV. Se necesita que todos los hitos cumplan con el objetivo de PMV para poder ser plasmados (en los siguientes objetivos) en código.

2024-10-03 07:28 UTC, mmnuria commented on docs/milestones.md
> ++ **HUs asociadas**: [HU001], [HU002], [HU003], [HU004], [HU005]
El hecho de asociar tantas HUs a un mismo milestone, es algo extenso para quien finalmente tenga que realizarlo. Según ha comentado el profesor en clase, para el objetivo 2, alguien tendrá que realizar tu milestone 0, por lo que, en este caso le habrías asignado el modelado de cada una de tu historia de usuario... Por otro lado (yo tambien estoy con el mismo problema en mi proyecto), creo que el objetivo del hito 0 debe ser orientado a la descripción detallada de la metodología que quieres utilizar para la realizacion de todo el proyecto, de manera que establezcas como vas a pasar del problema al codigo, mediante que metodologia. 

En definitiva, el hecho de mencionar "Analizar las historias de usuario y definir los requerimientos del sistema y los elementos del dominio." es algo ambiguo para alguien que se le asigne para el. objetivo 2 tu proyecto no crees? Piensa que serás quien tenga que aprobarselo y además, que con lo que te entregue puedas continuar trabajando con el resto de objetivos.

2024-10-03 10:40 UTC, juanmaaf approved these changes

2024-10-03 22:26 UTC, hossam1522 commented on docs/milestones.md
> ++ **HUs asociadas**: [HU001], [HU002], [HU003], [HU004], [HU005]
Buenas! He tenido en cuenta lo que has dicho y he considerado quitar la [HU005] del milestone 0 ya que este sería adicional en todo caso, pero los demás sí los considero necesarios. También he modificado el milestone 0 según lo que me has dicho. ¿Te importaría volver a revisarme? Gracias @mmnuria

2024-10-04 10:54 UTC, juanmaaf approved these changes

2024-10-04 10:57 UTC, antoniorr02 approved these changes
Viendo las modificaciones que has hecho en base a las recomendaciones de Juanma y Nuria, y los cambios que te he propuesto en persona, creo que cumples los requisitos para haber superado el objetivo. Tienes mi aprobación.

2024-10-04 11:05 UTC, hossam1522 commented
Le solicito una revisión a usted también @jj, ya que ya hay un par de compañeros que me la han aceptado. Gracias de antemano!

2024-10-04 12:19 UTC, mmnuria approved these changes
Por mi parte tienes el aprobado! Muy buen trabajo :)

2024-10-04 18:33 UTC, JJ requested changes
Es esencial resolver todos los comentarios para avanzar hacia la superación del objetivo. Si no los resuelves, fuerzas a quien venga después a leer los comentarios también a ver si están resueltos, con lo que es doble trabajo.
Se cambia la línea sobre la que se hace el comentario o se indica el commit donde se ha hecho, Github lo linka automáticamente.

2024-10-04 18:33 UTC, JJ commented on docs/milestones.md
Tienes que resolver todos los comentarios, aunque al final se haya aprobado. Lo haces cambiando la línea o indicando dónde se ha hecho.
@mmnuria conviene también que los comentarios los hagas sobre la fila en sí. Si es un comentario general, mejor como comentario al PR o bien cuando termines el review pulsas en "comment" en vez de "request changes". Así no queda aquí, y no fuerzas a solucionarlo.

2024-10-04 18:33 UTC, JJ commented on docs/milestones.md
> ++ **Objetivo**: Analizar las historias de usuario y definir los requerimientos clave del dominio del problema que se van a abordar en el desarrollo del PMV. Se estructurarán los
En ningún momento aparece la palabra "requerimientos". No se trabaja con requisitos en desarrollo ágil. Los requisitos son satisfacer al cliente.

2024-10-04 18:33 UTC, JJ commented on docs/milestones.md
> +### [M1] Milestone 1: Auditoría completa del inventario
Igualmente tienes que resolverlos.

2024-10-05 11:01 UTC, hossam1522 commented on docs/milestones.md
Resuelto en https://github.com/hossam1522/ModaTrack/pull/7/commits/37e9bf2996886c1cc843c078020f5b2aea974e6e

2024-10-05 11:01 UTC, hossam1522 commented on docs/user_stories.md
Resuelto en https://github.com/hossam1522/ModaTrack/pull/7/commits/37e9bf2996886c1cc843c078020f5b2aea974e6e

2024-10-05 11:01 UTC, hossam1522 commented on docs/milestones.md
> +### [M1] Milestone 1: Auditoría completa del inventario
Resuelto en https://github.com/hossam1522/ModaTrack/pull/7/commits/37e9bf2996886c1cc843c078020f5b2aea974e6e

2024-10-05 11:02 UTC, hossam1522 commented on docs/milestones.md
> +### [M0] Milestone 0: Modelado del problema
Resuelto en https://github.com/hossam1522/ModaTrack/pull/7/commits/3cfc2ce241ca61a5903be5f06c6774225d1b43fe

2024-10-05 11:08 UTC, hossam1522 commented
Solicito revisión de nuevo, @JJ. Gracias de antemano.

2024-10-08 18:10 UTC, JJ requested changes
Agradezco a quien ha revisado este objetivo, pero me temo que hay problemas al menos en los milestones. Por favor, repásalos.

2024-10-08 18:10 UTC, JJ commented on docs/milestones.md
> ++ **HUs asociadas**: [HU001], [HU002], [HU003], [HU004]
¿No te parecen demasiadas HUs para empezar a trabajar? Recuerda que es esencial dividir el problema en partes, para que quede claro qué es lo que hay que hacer ahora.

2024-10-08 18:10 UTC, JJ commented on docs/milestones.md
> ++ **Viabilidad**: Cuando se haya completado el modelado y la planificación del problema, y que estos sean validados por el revisor y sean comprensibles para el equipo de desarrollo.
¿el problema definido en qué HUs? ¿En todas? ¿En las primeras?

2024-10-08 18:10 UTC, JJ commented on docs/milestones.md
> ++ **HUs asociadas**: [HU001], [HU003]
Las HUs sólo se asocian temporalmente a los milestones. Por otra parte, si a esto están asociadas la 1 y la *3* no las estás secuenciando correctamente. Y si estás trabajando en el milestone 0 con cuatro HUs pero luego no vas a necesitar el modelo completo, no estás haciendo un producto mínimamente viable.

2024-10-08 18:10 UTC, JJ commented on docs/milestones.md
> +### [M1] Milestone 1: Auditoría completa del inventario
Me temo que esto no está resuelto. En parte @juanmaaf tiene razón, pero el problema mayor no es ese, sino que estás especificando una solución (hacer inventario). Las soluciones tienen que emerger del proceso de desarrollo. Un milestone nunca puede especificar una solución, sino qué es lo que hace una solución viable.

2024-10-09 21:02 UTC, hossam1522 commented on docs/milestones.md
> ++ **Viabilidad**: Cuando se haya completado el modelado y la planificación del problema, y que estos sean validados por el revisor y sean comprensibles para el equipo de desarrollo.
Resuelto en https://github.com/hossam1522/ModaTrack/pull/7/commits/69881da98ae268431a4d07f4f71def7c8adb181b

2024-10-09 21:30 UTC, hossam1522 commented on docs/milestones.md
> +### [M1] Milestone 1: Auditoría completa del inventario
En principio, resuelto en https://github.com/hossam1522/ModaTrack/pull/7/commits/e5ec11385fc58495fec416c9f134391378f4f67f y https://github.com/hossam1522/ModaTrack/pull/7/commits/6055d42d6b17f69ee4e08f9a22743790e80cc4e1 (en este último solo he actualizado el título del milestone 1, porque la separación del milestone en otros más pequeños la hice anteriormente en https://github.com/hossam1522/ModaTrack/commit/37e9bf2996886c1cc843c078020f5b2aea974e6e)

2024-10-10 05:43 UTC, JJ commented on docs/milestones.md
> +### [M1] Milestone 1: Auditoría completa del inventario
Si sigue sin cambiarse el título, sigue sin resolverse. Una *auditoría completa* ni siquiera es la descripción de un producto, por no mencionar si es mínimo o si es viable.

2024-10-10 05:46 UTC, JJ requested changes
Os recuerdo también [la introducción a los errores frecuentes del objetivo 0](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md#sobre-el-código-definido)

2024-10-10 05:46 UTC, JJ commented on docs/milestones.md
> ++ **Objetivo**: Analizar las historias de usuario y definir los elementos clave del dominio del problema que se van a abordar en el desarrollo del PMV. Se estructurarán los
¿Hay algún sitio en el guión donde pida un objetivo?

2024-10-10 07:45 UTC, JJ requested changes
Al final, la pregunta que tienes que hacerte siempre es la misma. Con el milestone 0 (al menos) ¿es suficiente para que la persona a la que se le asigne se ponga a trabajar? (Contesta a qué hago ahora) ¿Puede tener alguna indicación si lo que ha hecho está bien? (Segunda pregunta)

2024-10-10 07:45 UTC, JJ commented on docs/milestones.md
> +### [M0] Milestone 0: Modelado del problema
Sigue poniendo modelado, que es una actividad. Recuerda que los milestones son PMVs, productos.

2024-10-10 07:45 UTC, JJ commented on docs/milestones.md
> +Hay que entregar un modelo inicial del dominio del problema, con los conceptos clave y sus relaciones, definiendo las entidades y agregados necesarios para el desarrollo del PMV,
¿Dónde está contenido ese problema? Por favor, consulta [los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md):

> Aunque los milestones en principio no tienen por qué tener información sobre las historias de usuario, si hay varias historias de usuario hablar de "modelo del problema" o de "lógica de negocio" no es suficiente, porque las dos historias de usuario (o las 5) pueden tener diferentes aspectos del problema, o incluso ser problemas diferentes.

2024-10-11 05:22 UTC, JJ approved these changes
:+1: 
Recordad trasladar a milestones y HU en Github esto que está aprobado.

2024-10-11 11:20 UTC, merged