[IV-24-25] Objetivo 2
hossam1522/ModaTrack pull request #9
Opened 2024-10-18 12:16 UTC by juanbarearojo

2024-10-20 16:27 UTC, juanbarearojo commented
@hossam1522 Ya está listo.

2024-10-22 21:55 UTC, hossam1522 reviewed
En general veo bien tu solución, aunque te he dejado un par de comentarios. También quería comentar que creo que el nombre de los commits es erróneo, ya que falta el término `closes` antes del número de la issue que se cierra con ese preciso commit.

2024-10-22 21:55 UTC, hossam1522 commented on internal/models/productoVendido.go
> +	PrecioVenta int
¿No sería conveniente también meter el precio del producto dentro de la información de ese producto? ¿Qué opinas?

2024-10-23 07:49 UTC, juanbarearojo commented on internal/models/productoVendido.go
> +}
Para establecer lo siguiente. La historia de usuario hablaba de registrar un venta. Elegí la estructura establecida debido a que se consideraba mas limpio. Poner un vector de prodcuto vendido lo veía mas seguro ante fallos que una matriz con el producto y el precio de la venta. La lógica es la siguiente. En la venta del 20 de octubre se vendieron 2 pantalones de talla m a un precio de 20(estaba oferta) y una camisa a 30. Además de quela clase  ropa representa un modelo mas que un objeto en específico.

2024-10-23 13:35 UTC, juanbarearojo commented on internal/models/productoVendido.go
> +	PrecioVenta int
lo planteé pero me preocupaba repetir información ya que podría causar incossitencias

2024-10-23 20:26 UTC, hossam1522 reviewed
En general lo veo bien, ¡muy buen trabajo! Sin embargo, te comento un par de cosillas que, sinceramente, me gustaría que le dieses alguna vuelta y lo considerases.

2024-10-23 20:26 UTC, hossam1522 commented on internal/models/ropa.go
> +}
A la hora de representar la ropa, ¿no has pensado en la posibilidad de incluir un precio de compra de esta? Es algo que normalmente suele ser relevante a la hora de representarla.

2024-10-23 20:26 UTC, hossam1522 commented on internal/models/ropa.go
> +}
También comentas en la descripción del commit https://github.com/hossam1522/ModaTrack/pull/9/commits/c02c385a7872968a91c21fb5639b399984bf6d09 que cada instancia de la clase Ropa representa un modelo y una talla específica manteniendo el mismo nombre que las demás instancias con otras tallas.

Pero en caso de querer diferencias las tallas, ¿no crees que sería un lío hacerlo con el ID para, por ejemplo, saber cuánto stock me queda de una determinada talla de un determinado modelo, en relación con la [HU001](https://github.com/hossam1522/ModaTrack/blob/main/docs/user_stories.md#hu001-due%C3%B1o-de-tienda)?

A lo que voy, ¿no crees conveniente añadir un campo que indique la talla de la instancia? Eso haría más sencillo averiguar a qué talla del mismo modelo nos estamos refiriendo porque, por ejemplo, suponiendo que tengo "Pantalón Lacoste Mujer Negro" con IDs 5,6,7,8,9, ¿cómo diferencio la talla si por alguna casualidad no estuvieran introducidas en orden?

2024-10-24 12:19 UTC, juanbarearojo commented on internal/models/ropa.go
> +}
Había considerado que talla fuera parte del id pero es verdad todo lo que planteas.

2024-10-25 16:43 UTC, hossam1522 reviewed
Te dejo algunos comentarios. ¡Mucho ánimo!

2024-10-25 16:43 UTC, hossam1522 commented on internal/models/talla.go
> +Planteado un struct talla
Creo que se te ha escapado esto al hacer el commit

2024-10-25 16:43 UTC, hossam1522 commented on internal/models/ropa.go
> +	id              int
Un objeto valor no debe tener ningún ID asociado. Es simplemente un objeto el cual es inmutable.

2024-10-25 16:43 UTC, hossam1522 commented on internal/models/talla.go
> +)
Realmente no sé qué tan correcto sería pero, ¿no has considerado meter esto dentro del archivo ropa.go en vez de tenerlo por separado? Porque no sé si le llego a ver el sentido. ¿Qué opinas?

2024-10-31 09:44 UTC, juanbarearojo commented on internal/models/talla.go
> +)
lo planteé pero me parecía mas correcto que en cada archivo hubiera un clase/struct para mantener los archivos limpios

2024-10-31 10:03 UTC, juanbarearojo commented
@hossam1522 corregido los fallos

2024-10-31 11:48 UTC, juanbarearojo commented
Pruebas de compilacion. Go cuando no hay fallo no muestra errores
![image](https://github.com/user-attachments/assets/773a3e35-5377-4660-a9cf-8f993aaff1b6)

2024-11-01 18:31 UTC, hossam1522 commented
Viendo los cambios realizados, considero que el objetivo ya se puede considerar como superado. ¡Buen trabajo!

2024-11-01 18:31 UTC, hossam1522 submitted a review, later dismissed

2024-11-02 16:51 UTC, juanbarearojo commented
@jj Ya está listo para revisión. Gracias de antemano

2024-11-02 18:25 UTC, JJ requested changes
Aparte de lo dicho, ¿estás segudo @hossam1522 de que no faltan cosas en el modelo?

2024-11-05 11:03 UTC, juanbarearojo commented on internal/models/talla.go
> +	XL Talla = "XL"
Fue una decisión genérica se podría añadir mas tallas tanto por arriba como por abajo.

2024-11-05 11:05 UTC, juanbarearojo commented on internal/models/vendido.go
> +	precioVenta int
En este caso hay un precio tanto en el producto como ne la venta. Porque se supone que puede haber un precio base pero que se puede cambiar a la hora de la venta por diversos motivos (regateo, ofertas, cupones, etc)

2024-11-05 11:10 UTC, juanbarearojo commented on internal/models/venta.go
> +	itemsVendidos []ProductoVendido
Totalemente de acuerdo no lo había llegado a pensar

2024-11-05 11:13 UTC, juanbarearojo commented on internal/models/venta.go
> +	fecha         time.Time
Puedo introducir un constructor de tal forma que solo se introduzcan los productos de la venta. La fecha sea aquella del momento que se ha creado así podemos hacer que haya fechas válidas

2024-11-05 11:20 UTC, juanbarearojo commented on internal/models/vendido.go
> +	producto    *Ropa
Esta parte del código se hizo con el objetivo de evitar la existencia de punteros a valores nulos. No queremos repetir tampoco información repetida. Por eso como se estableció en el 52940e35fb7bee8bf4f41f2a475587289050afa9 se eligió un puntero para esto. Se planteó esta solución sobretodo por la busqueda de una solución segura y a prueba de fallos.

2024-11-05 11:29 UTC, juanbarearojo commented on internal/models/ropa.go
> +	cantidadEnStock int
En este caso entiendo que los objetos de valor son aquellos que son definidos por su atributos no por su entidad. Es verdad que al plantear una CantidadEnStock estamos convirtiéndolo en una entidad. La posible solución que se me ocurre es plantear una entidad stock que sea inventario que tenga objetos de valor del tipo ropa y una cantidad asociada. Pero no estoy seguro de la utilidad de esta.

2024-11-05 13:39 UTC, JJ commented on internal/models/vendido.go
> +	producto    *Ropa
Como te digo, a veces hay que pensar en el modelo antes que en la implementación. Si solo quieres implementar esto en memoria, podría ser correcto. En todo caso tampoco es un obstáculo si a @hossam1522 no se lo parece. Es él el que se tiene que ver trabajando con esto en el objetivo 4.

2024-11-05 13:39 UTC, JJ commented on internal/models/vendido.go
> +	precioVenta int
¿Eso está en la HU?

2024-11-05 13:40 UTC, JJ commented on internal/models/venta.go
> +	itemsVendidos []ProductoVendido
¿Qué dice la HU que va a hacerse con esto?
Recorrer un array e ir mirando cosas de los objetos de ese array no es muy eficiente, ¿no te parece?

2024-11-05 15:56 UTC, juanbarearojo commented on internal/models/vendido.go
> +	precioVenta int
Cierto que este concepto no es planteado en la HU por lo tanto debería ser eliminado. Siguiendo la metodología en este milestone debemos reflejar solo aquellos elementos planteados en las HU por lo que no se trata de añadir información innecesaria.

2024-11-05 16:02 UTC, juanbarearojo commented on internal/models/venta.go
> +	itemsVendidos []ProductoVendido
Es verdad que había pasado por alto el detalle que ese establece la gran cantidad de productos y ventas que hay. Además establece una restricción clara al decir  _**no me sobra tiempo como para ir mirándolo manualmente**_ por lo que debo buscar una estructura que permita al dueño de la tienda realizar estas búsquedas de manera eficiente, rápida y que este ordenada para que sea algo fácil para él. Esta es la necesidad del usuario

2024-11-05 16:26 UTC, juanbarearojo commented on internal/models/vendido.go
> +	precioVenta int
Partiendo de esta eliminación. Producto vendido pierde su validez ya que no aporta nada al cliente. Ya que una implementación que permita el usuario el acceso rápido a esta cantidad vendida provoca hace que no sea necesario establecer un atributo de cantidad y por ende productoVendido deja de ser objeto de valor.

2024-11-05 17:03 UTC, juanbarearojo commented
@hossam1522 Cuando puedas revisa los cmabios realizados para ver si estas de acuerdo con ellos. Gracias de antemano

2024-11-06 22:46 UTC, hossam1522 commented on internal/models/stock.go
> +}
En vez de hacer un struct, ¿no sería conveniente hacer algo del tipo:
```go
type Stock map[Ropa]int
```
?

Porque igual no tiene demasiado sentido un struct con un único atributo

2024-11-06 22:46 UTC, hossam1522 commented on internal/models/venta.go
> +}
Comentas en https://github.com/hossam1522/ModaTrack/pull/9/commits/cb4a4b5560cea9ca46cad155ca8449b450f3dbcd que las ventas importantes serán a partir de la implementación del sistema, pero esto no me parece correcto. Por ejemplo, se me ocurre el siguiente caso:

- Si quisiera comprobar el funcionamiento del sistema, sería conveniente poder introducir ventas antiguas para comprobar que la actualización del stock se hace correctamente

Igual habría que buscar otra forma de representar las fechas, prescindiendo igual de la biblioteca time o poniendo más u otras comprobaciones en el constructor.

2024-11-06 23:24 UTC, juanbarearojo commented on internal/models/venta.go
> +}
Lo veo bien pero necesitaría que en la HU pusiera en algún lado a partir de cuando que se considera fecha válida. Es decir con saber. Lo digo más que nada para poder poner un limite por abajo. Veo muy válido que se quieran introducir ventas anteriores pero es lo que decía tiene que haber límite para considerar que fecha es válida y cuál no.

2024-11-06 23:32 UTC, juanbarearojo commented on internal/models/stock.go
> +}
Se había establecido como struct para poder definir métodos más adelante de acceso. Esto permite una mejor gestión de la inmutabilidad, especialmente porque encapsulas el mapa inventario dentro de una struct. Esto permite un mayor control sobre el acceso y modificación de los datos, lo cual contribuye a mantener la inmutabilidad o al menos a restringir la modificación directa. Pero si es un poco según como vayas a tratarlo tú en el objetivo 4.

2024-11-07 09:05 UTC, hossam1522 commented on internal/models/venta.go
> +}
Tienes toda la razón del mundo, he modificado la HU para tener en cuenta esto.

2024-11-07 09:35 UTC, juanbarearojo commented on internal/models/venta.go
> +}
Muchas gracias

2024-11-07 11:49 UTC, hossam1522 approved these changes
Viendo que se ha arreglado lo comentado en https://github.com/hossam1522/ModaTrack/pull/9#discussion_r1831802518, considero correctos los cambios realizados.

2024-11-07 11:50 UTC, juanbarearojo commented
@JJ ya está listo para revisión

2024-11-07 12:00 UTC, juanbarearojo commented
@JJ Revisión porfavor.

2024-11-07 12:02 UTC, JJ approved these changes
👍

2024-11-07 13:19 UTC, merged